name: Manual Trashbox Parser

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run_parser]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run parser
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: python parser.py

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        touch sent_urls.txt
        git add sent_urls.txt
        if ! git diff --cached --quiet; then
          git commit -m "Update sent URLs database [skip ci]"
          git push
        else
          echo "Нет новых данных для сохранения."
        fi
